FROM mcr.microsoft.com/dotnet/sdk:10 AS build

ARG BUILD_CONFIGURATION=Release
WORKDIR /src

COPY ["Products.API/Products.API.csproj", "Products.API/"]
COPY ["Products.Core/Products.Core.csproj", "Products.Core/"]
COPY ["Products.Infrastructure/Products.Infrastructure.csproj", "Products.Infrastructure/"]

RUN dotnet restore "Products.API/Products.API.csproj"

COPY . .

WORKDIR /src/Products.API

RUN dotnet build "Products.API.csproj" \
    -c $BUILD_CONFIGURATION \
    -o /app/build


FROM build AS publish

ARG BUILD_CONFIGURATION=Release

RUN dotnet publish "Products.API.csproj" \
    -c $BUILD_CONFIGURATION \
    -o /app/publish \
    /p:UseAppHost=false


FROM mcr.microsoft.com/dotnet/aspnet:10 AS final

WORKDIR /app

EXPOSE 7275

COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet", "Products.dll"]
